### ISSUE TITLE
Found 0 images in album

### ISSUE THREAD

**Issue by EuanR** [alexgisby/imgur-album-downloader#15]
For some unknown reason I cannot download any albums. It tries to download them, however it finds 0 images. I can tell that it has still worked apart from that, as the folder is still created.

**Comment by alexgisby** [comment]
How bizarre! Give me a couple of hours to get home and I'll take a look.

Got an example of an album you're trying to download that isn't working? In fact, could you copy/paste the exact command you're running?

Thanks!

**Comment by EuanR** [comment]
Thanks for the reply, I have taken a screen shot of the command prompt and the destination for the album.
![screenshot_1](https://cloud.githubusercontent.com/assets/11723644/10052335/4007d99a-621e-11e5-95bb-549bc80294cf.jpg)

**Comment by alexgisby** [comment]
Amazing, thanks very much, I'll look into it!

**Comment by alexgisby** [comment]
Hey Euan,

I've created a pull request with a fix (see above, or the https://github.com/alexgisby/imgur-album-downloader/tree/bugfix/15-zero-images-found branch). Could you give it a test and see if that's working for you?

Seems like the little trick I was using to read all the images has been broken/removed by imgur, but there's another way that seems to work!

Alex

**Comment by EuanR** [comment]
That seems to have fixed the issue. I appreciate your quick assistance.

**Comment by alexgisby** [comment]
Awesome, I'll get that PR merged then! Glad to help :)
