### ISSUE TITLE
Images saved are currently significantly reduced in size

### ISSUE THREAD

**Issue by grimman** [alexgisby/imgur-album-downloader#17]
Since the breakage and subsequent fix a week ago, the images downloaded by the script are now significantly smaller both in terms of size and dimensions.

I verified with this album (containing three images) by downloading manually and then with the script: https://imgur.com/a/zOzQn

![album-comparison](https://cloud.githubusercontent.com/assets/594038/10157368/d2aa8d64-6689-11e5-8a57-f3543e744cb4.png)

**Comment by alexgisby** [comment]
Ah that's a feature, I'm just thinking about saving you all some hard drive space. ;)

Yeah, I've clearly screwed up how the script calculates the bigger image URL since the change, will have a look at that today. 

Thanks for the report!

**Comment by alexgisby** [comment]
Yeah I added an 'h' where it wasn't wanted, meaning hi-res rather than full-res. Excellent spot!

Have committed to master, so give it a pull and a test and see if that fixes your problem.

**Comment by grimman** [comment]
Ran the script on the same folder, and the files now match up to the very last byte. I'd say it was successful. :)

**Comment by alexgisby** [comment]
Excellent news! I'll close this off then! :)
